from django.urls import path
from rest_framework_simplejwt.views import TokenRefreshView
from . import views

urlpatterns = [
    path("auth/register/", views.register),
    path("auth/verify/", views.verify_email),
    path("auth/login/", views.login),
    path("auth/refresh/", TokenRefreshView.as_view()),
    path("auth/me/", views.me),
    path("auth/profile/", views.update_profile),
    path("auth/redeem-key/", views.redeem_key),
    path("documents/upload/", views.upload_document),
    path("documents/<int:doc_id>/ocr/", views.run_ocr),
    path("documents/<int:doc_id>/translate/", views.translate_document),
    path("documents/full-translate/", views.full_translate),
    path("documents/blank/", views.blank_document),
    path("templates/", views.list_templates),
    path("templates/create/", views.create_template),
    path("templates/<int:template_id>/fill/", views.fill_template),
    path("site-settings/", views.site_settings),
    path("site-settings/update/", views.update_site_settings),
    path("admin/users/", views.admin_users),
    path("admin/users/create/", views.admin_create_user),
    path("admin/users/<int:user_id>/delete/", views.admin_delete_user),
    path("admin/logs/", views.admin_logs),
    path("admin/premium-keys/", views.admin_premium_keys),
    path("admin/api-keys/", views.admin_api_keys),
    path("admin/ocr-status/", views.admin_ocr_status),
    path("admin/support-requests/", views.admin_support_requests),
    path("admin/support-requests/<int:request_id>/update/", views.admin_support_request_update),
    path("admin/templates/<int:template_id>/fields/", views.admin_add_template_field),
    path("admin/templates/<int:template_id>/delete/", views.admin_delete_template),
    path("admin/templates/<int:template_id>/fields/<int:field_id>/delete/", views.admin_delete_template_field),
    path("admin/templates/<int:template_id>/fields/<int:field_id>/update/", views.admin_update_template_field),
    path("admin/analytics/", views.admin_analytics),
    path("admin/premium-requests/", views.admin_premium_requests),
    path("admin/premium-requests/<int:request_id>/approve/", views.admin_approve_request),
    path("admin/premium-requests/<int:request_id>/reject/", views.admin_reject_request),
    path("admin/activity-logs/", views.admin_activity_logs),
    path("admin/ai-chat-logs/", views.admin_ai_chat_logs),
    path("ai/chat/", views.ai_chat),
    path("auth/logout/", views.logout),
    path("premium-requests/create/", views.create_premium_request),
    path("premium-requests/my/", views.my_premium_requests),
]
