# Generated by Django 5.0.6 on 2026-01-23 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_sitesettings_blackbox_api_key_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='blackbox_repo_url',
            field=models.CharField(blank=True, max_length=300),
        ),
    ]
